### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by ucalyptus** [ucalyptus/Detecting-Ships#2]

**Comment by dougfabris** [comment]
Hey @ucalyptus Can I help you with this? If yes, provide me some info to get started and run project locally.

**Comment by ucalyptus** [comment]
@dougfabris Thanks for joining in. Here are some overall goals we can achieve:

- Changing the formatting and contents of README ( suggestions are welcome )
- Description for each headline
- Reducing the size of the carbon now code images ( too big for good appeal )
- Lastly, a paragraph on this project. No need to write motivation, just about what it is.

Hope that helps.

**Comment by ucalyptus** [comment]
@dougfabris  any updates?

**Comment by dougfabris** [comment]
@ucalyptus I'm really busy this week mate. But I'll try to send a PR this week.
